document:
  dsl: 1.0.0
  namespace: zigflow
  name: conditional
  version: 0.0.1
  title: Conditional Tasks
  summary: Execute tasks conditionally
  metadata:
    display: false
input:
  schema:
    format: json
    document:
      type: object
      required:
        - integer
      properties:
        integer:
          type: number
timeout:
  after:
    minutes: 1
do:
  # If input is even, wait 5 seconds
  - waitIfEven:
      if: ${ $input.integer % 2 == 0 }
      export:
        as:
          task: even
      wait:
        seconds: 5
  # If input is odd, wait 10 seconds
  - waitIfOdd:
      if: ${ $input.integer % 2 == 1 }
      export:
        as:
          task: odd
      wait:
        seconds: 10
  # Always wait 5 seconds at the end
  - wait:
      output:
        as: ${ $context }
      wait:
        seconds: 5
