document:
  dsl: 1.0.0
  namespace: zigflow
  name: hello-world
  version: 0.0.1
  title: Hello World Encrypted
  summary: Hello world with Zigflow, but [encrypted](https://github.com/mrsimonemms/temporal-codec-server)
  metadata:
    display: false
do:
  - set:
      output:
        as:
          data: ${ . }
      set:
        message: Hello from Ziggy
