document:
  dsl: 1.0.0
  namespace: zigflow # Mapped to the task queue
  name: try-catch # Workflow name
  version: 0.0.1
  title: Try/Catch
  summary: An example of how to catch an erroring workflow
do:
  - user:
      export:
        as: user
      try:
        - getUser:
            call: http
            export:
              as: user
            with:
              method: get
              endpoint: https://jsonplaceholder.typicode.com/users/2000
      catch:
        do:
          - setError:
              export:
                as: err
              set:
                err: some error
