document:
  dsl: 1.0.0
  namespace: zigflow
  name: try-catch
  version: 0.0.1
  title: Try/Catch
  summary: An example of how to catch an erroring workflow
  metadata:
    display: false
do:
  - user:
      try:
        - getUser:
            call: http
            with:
              method: get
              endpoint: https://jsonplaceholder.typicode.com/users/2000
      catch:
        do:
          - setError:
              set:
                err: some error
