document:
  dsl: 1.0.0
  namespace: zigflow
  name: raise
  version: 0.0.1
  title: Throw an error
  summary: Throw an error from a Temporal workflow
  metadata:
    display: false
timeout:
  after:
    minutes: 1
do:
  - wait:
      wait:
        seconds: 1
  - error:
      raise:
        error:
          type: https://serverlessworkflow.io/spec/1.0.0/errors/communication
          status: 400
