name: Feature request
description: Suggest an idea or improvement for Zigflow.
title: "feat: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: >
        Before submitting, please search for existing issues to avoid
        duplicates, and read
        [CONTRIBUTING.md](https://github.com/mrsimonemms/zigflow/blob/main/CONTRIBUTING.md).
        If this is a significant change, please open a discussion issue
        first.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have read CONTRIBUTING.md
          required: true
        - label: I have searched for existing issues
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: desired
    attributes:
      label: Desired behaviour
      description: What do you want to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Any alternative approaches you have considered?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or references.
    validations:
      required: false
