# Temporal activity call example workflow
# Run alongside the DSL worker to execute custom activities
document:
  dsl: 1.0.0
  namespace: zigflow
  name: activity-call
  version: 0.0.1
  title: Activity Call Workflow
  summary: Invoke a Temporal activity from Zigflow
input:
  schema:
    format: json
    document:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          description: External user identifier
timeout:
  after:
    minutes: 1
do:
  - captureInput:
      set:
        requestedUserId: ${ $input.userId }
        requestId: ${ uuid }
  - fetchProfile:
      call: activity
      with:
          name: activitycall.FetchProfile
          arguments:
            - ${ $data.requestedUserId }
            - ${ $data.requestId }
          taskQueue: activity-call-worker
  - generateWelcome:
      call: activity
      with:
        name: activitycall.GenerateWelcome
        arguments:
          - ${ $data.fetchProfile }
        taskQueue: activity-call-worker
  - finalize:
      set:
        workflowId: ${ $data.requestId }
        profile: ${ $data.fetchProfile }
        message: ${ $data.generateWelcome.message }
