/*
 * Copyright 2025 - 2026 Zigflow authors <https://github.com/mrsimonemms/zigflow/graphs/contributors>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {
  addForkBranch,
  addNode,
  addSwitchBranch,
  createForkNode,
  createLoopNode,
  createSetNode,
  createSwitchNode,
  createTryNode,
  createWaitNode,
  createWorkflowFile,
  emptyFlowGraph,
} from '$lib/tasks/actions';
import type { FlowGraph, WorkflowFile } from '$lib/tasks/model';
import type { PageServerLoad } from './$types';

// ---------------------------------------------------------------------------
// Demo workflow construction
//
// buildDemoFile creates a representative sequential workflow. All node and
// branch IDs are generated by the factory functions (crypto.randomUUID()) with
// node.id === metadata.__zigflow_id — no name-derived or hardcoded IDs.
// ---------------------------------------------------------------------------

function buildDemoFile(): WorkflowFile {
  const file = createWorkflowFile({
    dsl: '1.0.0',
    namespace: 'demo',
    name: 'my-workflow',
    version: '0.0.1',
    title: 'Demo Workflow',
  });

  const rootId = file.order[0]!;

  let root: FlowGraph = emptyFlowGraph();

  const greet = createSetNode('greet', { message: 'Hello, World!' });
  root = addNode(root, greet);

  const pause = createWaitNode('pause', { duration: { seconds: 5 } });
  root = addNode(root, pause);

  let switchNode = createSwitchNode('route');
  switchNode = addSwitchBranch(switchNode, 'fast-path', '${ $input.fast == true }');
  switchNode = addSwitchBranch(switchNode, 'default');
  root = addNode(root, switchNode);

  let fork = createForkNode('parallel-work');
  fork = addForkBranch(fork, 'branch-a');
  fork = addForkBranch(fork, 'branch-b');
  root = addNode(root, fork);

  const tryNode = createTryNode('safe-call');
  root = addNode(root, tryNode);

  const loop = createLoopNode('process-items', '${ $input.items }');
  root = addNode(root, loop);

  return {
    ...file,
    workflows: {
      ...file.workflows,
      [rootId]: { ...file.workflows[rootId]!, root },
    },
  };
}

// Module-level singleton — server-only (never runs in the browser).
//
// In SvelteKit's server environment, this module is evaluated once per server
// process. All requests within a session use the same demo file and the same
// node UUIDs. This ensures that a URL such as ?selected=<uuid> remains
// resolvable across page reloads within a test or development session,
// matching the guarantee a real workflow provides through persisted YAML.
const _demoFile = buildDemoFile();

export const load: PageServerLoad = () => ({
  demoFile: _demoFile,
});
