document:
  dsl: 1.0.0
  namespace: zigflow # Mapped to the task queue
  name: external-calls # Workflow name
  version: 0.0.1
  title: External Calls
  summary: An example of how to use Serverless Workflow to make external calls
do:
  - fork:
      fork:
        compete: false
        branches:
          - grpc:
              call: grpc
              with:
                proto:
                  endpoint: file:///go/app/examples/external-calls/grpc/basic/proto/basic/v1/basic.proto
                service:
                  name: providers.v1.BasicService
                  host: grpc
                  port: 3000
                method: Command1
                arguments:
                  input: ${ $env.GRPC_INPUT }
          - http:
              call: http
              with:
                  method: get
                  endpoint: https://jsonplaceholder.typicode.com/users/3
