document:
  dsl: 1.0.0
  namespace: zigflow
  name: hello-world
  version: 0.0.1
  title: Hello World Encrypted Remote
  summary: Hello world with Zigflow, but remotely encrypted
  metadata:
    display: false
do:
  - set:
      output:
        as:
          data: ${ . }
      set:
        message: Hello from Ziggy
