document:
  dsl: 1.0.0
  namespace: zigflow
  name: run-task
  version: 0.0.1
  title: Run Task
  summary: How to execute code in NodeJS, Python and Shell
  metadata:
    display: false
timeout:
  after:
    minutes: 1
do:
  - container:
      export:
        as: '${ $context + { container: . } }'
      run:
        container:
          image: alpine
          arguments:
            - env
          environment:
            hello: world
  - nodejs:
      export:
        as: '${ $context + { nodejs: . } }'
      run:
        script:
          language: js
          code: |
            const http = require('http');

            console.log(`${process.argv[2]} from ${process.env.NAME}`);

            console.log(http.STATUS_CODES);
          arguments:
            - Hello
          environment:
            NAME: js
  - python:
      export:
        as: '${ $context + { python: . } }'
      run:
        script:
          language: python
          code: |
            import os
            import sys

            def main():
                arg = sys.argv[1] if len(sys.argv) > 1 else ""

                name = os.getenv("NAME", "")

                print(f"{arg} from {name}")

            if __name__ == "__main__":
                main()
          arguments:
            - Hello
          environment:
            NAME: python
  - shell:
      output:
        as: '${ $context + { shell: . } }'
      run:
        shell:
          command: ls
          arguments:
            - -la
