# This is a simple Serverless Workflow that will be
# translated into a Temporal workflow
document:
  dsl: 1.0.0
  namespace: zigflow # Mapped to the task queue
  name: run-task # Workflow name
  version: 0.0.1
  title: Run Task Workflow
  summary: An example of how to use Serverless Workflow to run scripts and shell commands
timeout:
  after:
    minutes: 1
do:
  - nodejs:
      export:
        as: nodejs
      run:
        script:
          language: js
          code: |
            const http = require('http');

            console.log(`${process.argv[2]} from ${process.env.NAME}`);

            console.log(http.STATUS_CODES[404]);
          arguments:
            - Hello
          environment:
            NAME: js
  - python:
      export:
        as: python
      run:
        script:
          language: python
          code: |
            import os
            import sys

            def main():
                arg = sys.argv[1] if len(sys.argv) > 1 else ""

                name = os.getenv("NAME", "")

                print(f"{arg} from {name}")

            if __name__ == "__main__":
                main()
          arguments:
            - Hello
          environment:
            NAME: python
